Lesson 14
vadzim-tseltseuski/thinknetica-test-guru pull request #14
Opened 2022-06-05 17:16 UTC by vadzim-tseltseuski

2022-06-06 07:03 UTC, VidgarVii requested changes

2022-06-06 07:03 UTC, VidgarVii commented on lib/clients/github_client.rb
> +class GithubClient
сомнительная участь класса. Как хттп клиент уже выступает Octokit::Client
Во 2 всё-ровно размазал логику и вытащил методы Octokit::Client аж в контроллер. Т.е. идея создания адаптера для упрощения работы и редактирования кода уже провалилась. Лишние зависимости уже просочились во внешние классы.
Предлагаю во все убрать этот класс. И использовать Octokit::Client в GistQuestionService. И следить за тем чтобы методы Octokit::Client не выходили за рамки GistQuestionService

2022-06-06 07:03 UTC, VidgarVii commented on lib/clients/github_client.rb
> +    ACCESS_TOKEN = ENV['GIST_TOKEN']
если GIST_TOKEN не будет. то ошибка будет на стороне октокит. Что не совсем корректно. Тем более ты эту ошибку зачем-то обрабатываешь. Лучше проверку токена делать явной. Для этого можно воспользоваться 
ENV.fetch('GIST_TOKEN')

2022-06-06 07:03 UTC, VidgarVii commented on lib/clients/github_client.rb
> +    #end
мусор!

2022-06-06 07:03 UTC, VidgarVii commented on app/views/shared/admin/_nav.html.erb
> +</nav>
в конце файла надо отставлять 1 пустую строчку. Это указатель на конец файла. Сейчас система думает, что происходит обрыв файла. Даже гитхаб ругается. No new lina at end of file

2022-06-07 06:14 UTC, vadzim-tseltseuski commented on app/controllers/test_passages_controller.rb
> +      url = result.html_url
Добавил struct response

2022-06-07 06:14 UTC, vadzim-tseltseuski commented on app/controllers/test_passages_controller.rb
> +    flash_options = if url
исправил

2022-06-07 06:15 UTC, vadzim-tseltseuski commented on app/services/gist_question_service.rb
> +    end
исправил

2022-06-07 06:15 UTC, vadzim-tseltseuski commented on app/services/gist_question_service.rb
> +    def initialize(question, client: nil)
удалил класс

2022-06-07 06:16 UTC, vadzim-tseltseuski commented on app/controllers/test_passages_controller.rb
> +  def gist
вот тут не совсем понял - о чем речь?

2022-06-07 07:03 UTC, VidgarVii requested changes

2022-06-07 07:03 UTC, VidgarVii commented on app/controllers/test_passages_controller.rb
> +      url = result.html_url
тут так же не исправил

2022-06-07 15:24 UTC, VidgarVii requested changes

2022-06-07 15:24 UTC, VidgarVii commented on Gemfile
> +gem 'faraday'
этот гем не будет больше использоваться. Стоит удалить

2022-06-07 15:24 UTC, VidgarVii commented on Gemfile
> +gem 'dotenv-rails', groups: [:development, :test]
парой строк ниже как раз есть группа development, :test. Стоит там указать этот гем

2022-06-07 15:24 UTC, VidgarVii commented on app/controllers/test_passages_controller.rb
> +  def gist
не исправил

2022-06-07 15:24 UTC, VidgarVii commented on app/controllers/test_passages_controller.rb
> +    flash_options = nil
такое определение переменной не к чему

2022-06-07 15:24 UTC, VidgarVii commented on app/services/gist_question_service.rb
> +end
No new lina at end of file 
с этим надо уже что-то делать

2022-06-07 15:24 UTC, VidgarVii commented on app/services/gist_question_service.rb
> +  GIST_TOKEN = ENV.fetch('GIST_TOKEN')
константу положить в константу ну такое решение =/

2022-06-07 15:24 UTC, VidgarVii commented on app/controllers/test_passages_controller.rb
> +      flash_options = { notice: t('.success', url: url) }
ссылка должна быть кликабельной. 
Советую более понятно называть ключи для локали

2022-06-08 06:26 UTC, VidgarVii requested changes

2022-06-08 06:26 UTC, VidgarVii commented on app/controllers/gists_controller.rb
> +  end
No new lina at end of file

2022-06-08 06:26 UTC, VidgarVii commented on app/controllers/test_passages_controller.rb
> +  before_action :set_test_passage, only: %i[show update result gist]
gist ?

2022-06-12 18:25 UTC, merged