Leeson 5
vadzim-tseltseuski/thinknetica-test-guru pull request #4
Opened 2022-02-19 18:48 UTC by vadzim-tseltseuski

Add associations to models, fix schema, delete redunant tabel

2022-02-20 09:31 UTC, VidgarVii requested changes

2022-02-20 09:31 UTC, VidgarVii commented on app/models/test.rb
> +  belongs_to :author, class_name: 'User', foreign_key: :author_id
вот эта связь в схеме указана не верно

2022-02-20 09:31 UTC, VidgarVii commented on app/models/category.rb
> +  has_many :tests
если категорию удалить, то в текущем варианте можно в дальнейшем получить ошибку

к примеру при попытке обратиться по ассоциации (`@test.category`)
или при каких-то операциях, которые подразумевают валидацию объекта

после удаления категории в таблице `tests` останется в поле `category_id` ссылка на несуществующий объект
т.е. объекты в таблице `tests` станут невалидными: рельсы по умолчанию проверяют наличие ассоциированного объекта для всех `belongs_to` ассоциаций (при валидации этого объекта) и выбрасывают ошибку валидации, если объекта не существует

если же на уровне бд поле `category_id` обозначено, как внешний ключ, то уже на попытке удаления объекта из таблицы `categories` получим ошибку базы данных, такого примерно вида:
```
ActiveRecord::InvalidForeignKey (PG::ForeignKeyViolation: EROR:  update or delete on table "categories" violates foreign key constraint
```
и рельсы откажутся удалять категорию

поэтому для всех `has_*` ассоциаций следует указывать поведение при удалении - можно посмотреть в документации - опция `dependent: ...`

2022-02-20 09:31 UTC, VidgarVii commented on app/models/question.rb
> +  belongs_to :test
belongs_to и has_many разделяют пустыми строками. Такое разделение кода на логические блоки.
Пример оформления модели можно посмотреть тут https://github.com/rubocop/rails-style-guide#macro-style-methods

2022-02-20 09:31 UTC, VidgarVii commented on app/models/question.rb
> +  belongs_to :test
Соблюдай очередность.
Принято сначала писать belongs_to далее ниже has_

2022-02-20 09:31 UTC, VidgarVii commented on app/models/test.rb
> +  belongs_to :category
достаточно 1 объявления belongs_to :category

2022-02-20 09:31 UTC, VidgarVii commented on app/models/test.rb
>      end
с использованием ассоциации `joins` можно сильно сократить
в задании "Ассоциации моделей" самое время это сделать

***
```ruby
  joins(:category)
    .where(categories: { title: category_title })
    .order(title: :desc)
    .pluck(:title)
```

2022-02-20 09:31 UTC, VidgarVii commented on app/models/user.rb
>      Test.joins('JOIN user_tests on tests.id = user_tests.test_id')
здесь в методе можно значительно упростить код
у тебя теперь есть ассоциация, которая вернет список всех тестов пользователя

2022-02-20 09:31 UTC, VidgarVii commented on db/seeds.rb
>  end
теперь, благодаря ассоциациям, можно (и рекомендуется в ООП) передавать объекты для связывания по ключам, вместо аттрибутов: `category: categories[0]`, `author: users[0]` и т.п. (без `_id` , `.id`)

2022-02-20 11:08 UTC, vadzim-tseltseuski commented on app/models/test.rb
> +  belongs_to :author, class_name: 'User', foreign_key: :author_id
Исправил.

2022-02-21 07:53 UTC, VidgarVii commented on app/models/test.rb
> +  has_many :users, through: :user_tests, dependent: :destroy
для has_many through достаточно 1 раз указать dependent

при удалении записи в таблице `users` будет удалена только запись из таблицы `tests_users`
таблица `:tests` никак не будет затронута (и также удаление в `tests` не затронет `users`)
удаление из таблицы `tests_users` правильное и нужное - зачем хранить связь между записями, если одна из них уже удалена?

небольшой [пост](https://makandracards.com/makandra/32175-don-t-forget-automatically-remove-join-records-on-has_many-through-associations) с рекомендацией относительно подобного случая

2022-02-21 08:09 UTC, vadzim-tseltseuski commented on app/models/test.rb
> +  has_many :users, through: :user_tests, dependent: :destroy
Вот как раз эту информацию искал. Но видимо мало искал. В оф доке что-то этот момент не очень описан был
Исправил

2022-02-21 08:12 UTC, merged